### ISSUE TITLE
Upload and delete new marker / privacy 

### ISSUE THREAD

**Issue by connectnet** [vitalidze/traccar-web#246] opened 2015-08-27 12:02 UTC
1. When I upload a new marker e.E. a private picture it is visible for all other users.
   Is it correct? No privacy?
2. At your sever it is possible to delete an uploaded pic but my server sends always an error.
   What is wrong at my side? (Mysql database is executed as root)

**Comment by vitalidze** [comment] 2015-08-27 12:28
1. No one requested the access management for the pictures.
2. Sounds like a bug. Can you please show the `wrapper.log` right after issue is reproduced?

**Comment by connectnet** [comment] 2015-08-27 12:47
1. If you are an investigator and you have to observe different objects its better to keep the pics safe.
2. Take a look at your server. Now I cant delete my uploaded pic at your server too. "Remote procedure call error"

**Comment by vitalidze** [comment] 2015-08-27 13:00
1. I don't quite get what you are talking about. Why should you pic marker icons safe? What will happen if someone finds your small car picture? I confirm that all other data (including big car Photo, car plate number, cell phone number) should be protected. I believe this is quite subjective.
2. I will take a look.

**Comment by connectnet** [comment] 2015-08-27 13:28
1. Ok. Ill upload some demo pics if it is possible again. ;-)

**Comment by vitalidze** [comment] 2015-08-28 07:11
Looks like you cannot delete a device icon when it is assigned to some device, which is a bug and will be fixed in next version.

**Comment by vitalidze** [comment] 2015-09-09 06:05
@connectnet issue with marker removal is fixed and can be tested both on demo site and in [0.8.1rc2](https://github.com/vitalidze/traccar-web/releases/tag/0.8.1rc2)

**Comment by connectnet** [comment] 2015-09-09 09:09
Hi Vitaly!
The removal bug is fixed but now every user can delete makers from others. That makes no sense?
I think it will be better to have "private" markers.

**Comment by vitalidze** [comment] 2015-09-09 09:15
I don't want to over-engineer these marker pictures, no one ever asked about this. Maybe it's worth to show some kind of warning when marker that is going to be deleted by the ordinary user is used for devices of different users. But both administrator and manager should be allowed to remove it.

**Comment by vitalidze** [comment] 2015-09-30 08:30
Implemented, written [news](http://traccar.litvak.su/2015/09/30/big-bugfix-release.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.

**Closed as completed by vitalidze** 2015-09-30 08:30 UTC
Labels: bug
