### ISSUE TITLE
Button style does not appear when used language Portuguese Brazil

### ISSUE THREAD

**Issue by rafaelolivei** [vitalidze/traccar-web#396] opened 2015-12-10 12:44 UTC
Hello!

Found you can not use the button style in other languages, including the (Portuguese in Brazil) . This so this button that appears in the English language.

regards
Rafael Oliveira

![styles](https://cloud.githubusercontent.com/assets/8041024/11715698/f030653c-9f2a-11e5-903c-7d6cd0a40f3b.jpg)

**Comment by vitalidze** [comment] 2015-12-10 12:55
This is a duplicate of #361. The reason is the small screen resolution of your machine, in which case the menu gets collapsed, however it hides the menu as well. I think I have found a way to fix it. But the label with the color will still not be visible in 'collapsed' state. All other menu will remain. The fix will be included in next version.

**Comment by vitalidze** [comment] 2015-12-10 16:30
Fixed, written [news](http://traccar.litvak.su/2015/12/10/Commands-bug-fix,-search-of-device,-visibility-control-for-devices.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) version.

**Closed as completed by vitalidze** 2015-12-10 16:30 UTC
Labels: bug, duplicate
