### ISSUE TITLE
Trafic Layer

### ISSUE THREAD

**Issue by mertturkman** [vitalidze/traccar-web#634] opened 2016-04-18 19:51 UTC
Can you add traffic layer google maps ?

**Comment by vitalidze** [comment] 2016-04-18 20:06
I think it is possible. Probably will be added in some future versions.

**Comment by mertturkman** [comment] 2016-04-18 20:11
Thanks a lot! I hope that as soon as you add.

**Comment by vitalidze** [comment] 2016-04-24 06:40
Closing as duplicate of #451

**Closed as completed by vitalidze** 2016-04-24 06:40 UTC
Labels: duplicate, enhancement, question
