### ISSUE TITLE
Latest reported Time Mismatch

### ISSUE THREAD

**Issue by abhishekricky** [vitalidze/traccar-web#471] opened 2016-01-13 13:07 UTC
Hi,

mismatch between user’s status displayed on the sidebar but I can see his todays position

Screenshot attached
![image](https://cloud.githubusercontent.com/assets/5213928/12295079/b76f9780-ba24-11e5-86df-2b66e3ada892.png)

**Comment by vitalidze** [comment] 2016-01-13 13:14
This is the data for different devices. The name is different even on screenshot. This bug is caused by filtering and is already fixed in latest available version.

**Comment by abhishekricky** [comment] 2016-01-13 13:44
![image](https://cloud.githubusercontent.com/assets/5213928/12295837/da38e3d4-ba29-11e5-9b01-0b53b603d64a.png)
  But here without any filter it shows same device with again now last online 1 day old

**Comment by vitalidze** [comment] 2016-01-13 14:31
This means your device reported last that position for some reason. You need to check last message came from your device in the `tracker-server.log` file.

**Closed as completed** 2016-03-08 03:47 UTC
Labels: duplicate, help wanted
