### ISSUE TITLE
Unable to delete user

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#551] opened 2016-03-04 10:26 UTC
Hello,

Please have a look at my picture.
Thanks.
I tried to  UNblock it and put it as  Administrator.... each time I want to delete .....

![deleteuser](https://cloud.githubusercontent.com/assets/15246747/13524487/9dda5c26-e24f-11e5-92a2-67f36486fc67.jpg)

**Comment by vitalidze** [comment] 2016-03-05 07:34
This looks like a bug. Please show contents of `wrapper.log` file right after you reproduce the issue.

**Comment by ghost** [comment] 2016-03-07 12:51
This is it 

```
INFO   | jvm 1    | 2016/03/07 23:48:31 | INFO: Login 'admin'
INFO   | jvm 1    | 2016/03/07 23:48:57 | [qtp12029085-64] WARN / - Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2016/03/07 23:48:57 | com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.traccar.web.shared.model.User org.traccar.web.client.model.DataService.removeUser(org.traccar.web.shared.model.User) throws org.traccar.web.shared.model.AccessDeniedException' threw an unexpected exception: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.eclipse.jetty.server.Server.handle(Server.java:499)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/03/07 23:48:57 | Caused by: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1763)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.throwPersistenceException(AbstractEntityManagerImpl.java:1771)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.hibernate.jpa.spi.AbstractQueryImpl.executeUpdate(AbstractQueryImpl.java:87)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.traccar.web.server.model.DataServiceImpl.removeUser(DataServiceImpl.java:349)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:41)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:41)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   ... 42 more
INFO   | jvm 1    | 2016/03/07 23:48:57 | Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:72)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:211)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.hibernate.hql.internal.ast.exec.BasicExecutor.doExecute(BasicExecutor.java:109)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.hibernate.hql.internal.ast.exec.BasicExecutor.execute(BasicExecutor.java:78)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.hibernate.hql.internal.ast.exec.DeleteExecutor.execute(DeleteExecutor.java:125)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.hibernate.hql.internal.ast.QueryTranslatorImpl.executeUpdate(QueryTranslatorImpl.java:445)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.hibernate.engine.query.spi.HQLQueryPlan.performExecuteUpdate(HQLQueryPlan.java:379)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.hibernate.internal.SessionImpl.executeUpdate(SessionImpl.java:1286)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.hibernate.internal.QueryImpl.executeUpdate(QueryImpl.java:118)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.hibernate.jpa.internal.QueryImpl.internalExecuteUpdate(QueryImpl.java:371)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.hibernate.jpa.spi.AbstractQueryImpl.executeUpdate(AbstractQueryImpl.java:78)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   ... 51 more
INFO   | jvm 1    | 2016/03/07 23:48:57 | Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails ("traccar"."notification_templates", CONSTRAINT "ntemplates_fkey_settings_id" FOREIGN KEY ("settings_id") REFERENCES "notification_settings" ("id"))
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.mysql.jdbc.Util.getInstance(Util.java:387)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:410)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
INFO   | jvm 1    | 2016/03/07 23:48:57 |   ... 60 more
```

**Comment by vitalidze** [comment] 2016-04-23 12:51
I have tried lightweight solution with the `background-size` [CSS3 attribute](http://stackoverflow.com/questions/9262861/css-background-image-to-fit-width-height-should-auto-scale-in-proportion), but unfortunately it scales small images as well. So, since big images is a rare case, I am closing this issue.

**Comment by vitalidze** [comment] 2016-04-25 09:05
Fixed, written [news](http://traccar.litvak.su/2016/04/25/Groups-tree-structure,-automatic-zoom,-direction-arrows-in-popup,-3.4-3.5-support.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.

**Closed as completed by vitalidze** 2016-04-25 09:05 UTC
Labels: bug
